# Site settings
title: Rubberduck
email: alex@rubberduck.fr 
description: > # this means to ignore newlines until "baseurl:"
  Alex is a web engineer specialized in the font end technologies, with
  a strong interest in data visualizations. He also has a backend background
  in Scala / PlayFramework2. This website presents his professional offer as
  a freelancer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rubberduck.fr" # the base hostname & protocol for your site
twitter_username: bobylito
github_username:  bobylito
linkedin_url: //lnkd.in/pGpKxY

# Build settings
markdown: kramdown
